branch-defaults:
  master:
    environment: covid-doctors-api-prod
    group_suffix: null
global:
  application_name: covid-doctors-api
  branch: null
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: 5vid-eb-deployment
  repository: null
  sc: git
  workspace_type: Application
